#!/bin/bash

vim +PlugUpdate +qa

cd /home/andrei/.vim/plugged/vim-fugitive/           && git reset --hard 0374322
cd /home/andrei/.vim/plugged/gitv/                   && git reset --hard 26758b8
cd /home/andrei/.vim/plugged/vim-unimpaired/         && git reset --hard 1bf6f16
cd /home/andrei/.vim/plugged/vim-surround/           && git reset --hard fa433e0
cd /home/andrei/.vim/plugged/vim-abolish/            && git reset --hard d932b44
cd /home/andrei/.vim/plugged/vim-bundler/            && git reset --hard 37096db
cd /home/andrei/.vim/plugged/vim-rake/               && git reset --hard 13533d9
cd /home/andrei/.vim/plugged/gem-ctags/              && git reset --hard 28c8cf5
cd /home/andrei/.vim/plugged/gem-browse/             && git reset --hard 1625ddc
cd /home/andrei/.vim/plugged/vim-rails/              && git reset --hard 7ac6b0b
cd /home/andrei/.vim/plugged/vim-repeat/             && git reset --hard 2a3c5f8
cd /home/andrei/.vim/plugged/vim-endwise/            && git reset --hard 6b83716
cd /home/andrei/.vim/plugged/vim-ruby/               && git reset --hard 5bc55be
cd /home/andrei/.vim/plugged/vim-rbenv/              && git reset --hard 79a3316
cd /home/andrei/.vim/plugged/vim-haml/               && git reset --hard 204e327
cd /home/andrei/.vim/plugged/vim-easymotion/         && git reset --hard 868cd71
cd /home/andrei/.vim/plugged/emmet-vim/              && git reset --hard 920904c
cd /home/andrei/.vim/plugged/tabular/                && git reset --hard 60f2564
cd /home/andrei/.vim/plugged/tComment/               && git reset --hard 34a1020
cd /home/andrei/.vim/plugged/numbers.vim/            && git reset --hard c7e0448
cd /home/andrei/.vim/plugged/vim-monokai/            && git reset --hard 168adea
cd /home/andrei/.vim/plugged/vim-addon-mw-utils/     && git reset --hard 0c5612f
cd /home/andrei/.vim/plugged/tlib_vim/               && git reset --hard bc4097b
cd /home/andrei/.vim/plugged/vim-snippets/           && git reset --hard 93f677f
cd /home/andrei/.vim/plugged/vim-tags/               && git reset --hard 2326af6
cd /home/andrei/.vim/plugged/tagbar/                 && git reset --hard 9ee516e
cd /home/andrei/.vim/plugged/EasyGrep/               && git reset --hard 9b938ec
cd /home/andrei/.vim/plugged/vim-debug/              && git reset --hard 1b0358a
cd /home/andrei/.vim/plugged/ag.vim/                 && git reset --hard d3a00f8
cd /home/andrei/.vim/plugged/greplace.vim/           && git reset --hard 475d567
cd /home/andrei/.vim/plugged/vim-airline/            && git reset --hard 825a048
cd /home/andrei/.vim/plugged/unite.vim/              && git reset --hard b54f168
cd /home/andrei/.vim/plugged/neomru.vim/             && git reset --hard f70be81
cd /home/andrei/.vim/plugged/unite-help/             && git reset --hard 5a8dc6c
cd /home/andrei/.vim/plugged/unite-outline/          && git reset --hard 20c30e2
cd /home/andrei/.vim/plugged/vim-unite-history/      && git reset --hard 73c766a
cd /home/andrei/.vim/plugged/unite-tag/              && git reset --hard 0dd146b
cd /home/andrei/.vim/plugged/unite-rails/            && git reset --hard 7bb902e
cd /home/andrei/.vim/plugged/unite-ruby-require.vim/ && git reset --hard c5b7d0f
cd /home/andrei/.vim/plugged/unite-rake/             && git reset --hard 8050686
cd /home/andrei/.vim/plugged/neocomplete/            && git reset --hard bdf5c4e
cd /home/andrei/.vim/plugged/neosnippet/             && git reset --hard ee1246a
cd /home/andrei/.vim/plugged/tern_for_vim/           && git reset --hard e27180e
cd /home/andrei/.vim/plugged/nerdtree/               && git reset --hard 4f1e6ec
cd /home/andrei/.vim/plugged/vimfiler.vim/           && git reset --hard 0986007
cd /home/andrei/.vim/plugged/neossh.vim/             && git reset --hard fdb2498
cd /home/andrei/.vim/plugged/vimshell.vim/           && git reset --hard 2c319d3
cd /home/andrei/.vim/plugged/vim-puppet/             && git reset --hard d881b93
cd /home/andrei/.vim/plugged/vim-ruby-refactoring/   && git reset --hard 6447a4d
cd /home/andrei/.vim/plugged/syntastic/              && git reset --hard 1e1c708
cd /home/andrei/.vim/plugged/vim-multiple-cursors/   && git reset --hard f948606
cd /home/andrei/.vim/plugged/vim-gitgutter/          && git reset --hard 1e82019
cd /home/andrei/.vim/plugged/copypath.vim/           && git reset --hard b7c5e7f
cd /home/andrei/.vim/plugged/vim-node/               && git reset --hard 07a5e9f
cd /home/andrei/.vim/plugged/vim-css-color/          && git reset --hard fb725aa
cd /home/andrei/.vim/plugged/delimitMate/            && git reset --hard 38487bb
cd /home/andrei/.vim/plugged/FuzzyFinder/            && git reset --hard b9f1659
cd /home/andrei/.vim/plugged/screen/                 && git reset --hard bd81d1c
cd /home/andrei/.vim/plugged/vimux/                  && git reset --hard 50254fa
cd /home/andrei/.vim/plugged/vim-signature/          && git reset --hard 3bc19dc
cd /home/andrei/.vim/plugged/vim-textobj-rubyblock/  && git reset --hard b5b84e4
cd /home/andrei/.vim/plugged/vim-textobj-user/       && git reset --hard 5256321
cd /home/andrei/.vim/plugged/vim-textobj-indent/     && git reset --hard deb7686
cd /home/andrei/.vim/plugged/vim-textobj-line/       && git reset --hard f8ab33c
cd /home/andrei/.vim/plugged/vim-textobj-entire/     && git reset --hard 41c12e1
cd /home/andrei/.vim/plugged/vim-qargs/              && git reset --hard a5fbc37
cd /home/andrei/.vim/plugged/vim-expand-region/      && git reset --hard 9665135
cd /home/andrei/.vim/plugged/vim-jsdoc/              && git reset --hard 56d3c5b
cd /home/andrei/.vim/plugged/vim-togglelist/         && git reset --hard cafedc4
cd /home/andrei/.vim/plugged/dockerfile.vim/         && git reset --hard 04ad0c4
cd /home/andrei/.vim/plugged/vim-sneak/              && git reset --hard 2d9be7b
cd /home/andrei/.vim/plugged/vim-textobj-comment/    && git reset --hard 58ae457
cd /home/andrei/.vim/plugged/vim-coffee-script/      && git reset --hard 18c6852
cd /home/andrei/.vim/plugged/vim-auto-save/          && git reset --hard acb5cd5
cd /home/andrei/.vim/plugged/vim-textobj-indent/     && git reset --hard deb7686
cd /home/andrei/.vim/plugged/patchreview-vim/        && git reset --hard c48e67a
cd /home/andrei/.vim/plugged/vim-codereview/         && git reset --hard 247feb9
cd /home/andrei/.vim/plugged/vim-extradite/          && git reset --hard af4f3a5
cd /home/andrei/.vim/plugged/L9/                     && git reset --hard c822b05

