#!/bin/bash
# Generated by vim-plug
# Mon 06 Oct 2014 07:31:45 PM EEST

vim +PlugUpdate +qa

PLUG_HOME=~/.vim/bundle

cd $PLUG_HOME/EasyGrep/ && git reset --hard 9b938ec
cd $PLUG_HOME/FuzzyFinder/ && git reset --hard b9f1659
cd $PLUG_HOME/L9/ && git reset --hard c822b05
cd $PLUG_HOME/MatchTagAlways/ && git reset --hard ca74f05
cd $PLUG_HOME/ag.vim/ && git reset --hard d3a00f8
cd $PLUG_HOME/argarg.vim/ && git reset --hard 241a53d
cd $PLUG_HOME/copypath.vim/ && git reset --hard b7c5e7f
cd $PLUG_HOME/delimitMate/ && git reset --hard 38487bb
cd $PLUG_HOME/dockerfile.vim/ && git reset --hard 04ad0c4
cd $PLUG_HOME/emmet-vim/ && git reset --hard 920904c
cd $PLUG_HOME/gem-browse/ && git reset --hard 1625ddc
cd $PLUG_HOME/gem-ctags/ && git reset --hard 28c8cf5
cd $PLUG_HOME/gitv/ && git reset --hard 26758b8
cd $PLUG_HOME/greplace.vim/ && git reset --hard 475d567
cd $PLUG_HOME/neocomplete/ && git reset --hard bdf5c4e
cd $PLUG_HOME/neomru.vim/ && git reset --hard f70be81
cd $PLUG_HOME/neosnippet/ && git reset --hard ee1246a
cd $PLUG_HOME/neossh.vim/ && git reset --hard fdb2498
cd $PLUG_HOME/nerdtree/ && git reset --hard 4f1e6ec
cd $PLUG_HOME/numbers.vim/ && git reset --hard c7e0448
cd $PLUG_HOME/patchreview-vim/ && git reset --hard c48e67a
cd $PLUG_HOME/screen/ && git reset --hard bd81d1c
cd $PLUG_HOME/syntastic/ && git reset --hard 1e1c708
cd $PLUG_HOME/tComment/ && git reset --hard 34a1020
cd $PLUG_HOME/tabular/ && git reset --hard 60f2564
cd $PLUG_HOME/tagbar/ && git reset --hard f3a369c
cd $PLUG_HOME/tern_for_vim/ && git reset --hard e27180e
cd $PLUG_HOME/tlib_vim/ && git reset --hard bc4097b
cd $PLUG_HOME/unite-help/ && git reset --hard 5a8dc6c
cd $PLUG_HOME/unite-outline/ && git reset --hard bd2caad
cd $PLUG_HOME/unite-rails/ && git reset --hard 7bb902e
cd $PLUG_HOME/unite-rake/ && git reset --hard 8050686
cd $PLUG_HOME/unite-ruby-require.vim/ && git reset --hard c5b7d0f
cd $PLUG_HOME/unite-tag/ && git reset --hard 0dd146b
cd $PLUG_HOME/unite.vim/ && git reset --hard 76612ec
cd $PLUG_HOME/vim-abolish/ && git reset --hard d932b44
cd $PLUG_HOME/vim-addon-mw-utils/ && git reset --hard 0c5612f
cd $PLUG_HOME/vim-airline/ && git reset --hard 825a048
cd $PLUG_HOME/vim-auto-save/ && git reset --hard 2caf8a0
cd $PLUG_HOME/vim-bundler/ && git reset --hard 37096db
cd $PLUG_HOME/vim-capybara/ && git reset --hard 12d1645
cd $PLUG_HOME/vim-codereview/ && git reset --hard 247feb9
cd $PLUG_HOME/vim-coffee-script/ && git reset --hard 18c6852
cd $PLUG_HOME/vim-css-color/ && git reset --hard fb725aa
cd $PLUG_HOME/vim-cucumber/ && git reset --hard 8f48260
cd $PLUG_HOME/vim-debug/ && git reset --hard 1b0358a
cd $PLUG_HOME/vim-dispatch/ && git reset --hard 71499a6
cd $PLUG_HOME/vim-easymotion/ && git reset --hard 868cd71
cd $PLUG_HOME/vim-endwise/ && git reset --hard 96eb117
cd $PLUG_HOME/vim-expand-region/ && git reset --hard 9665135
cd $PLUG_HOME/vim-extradite/ && git reset --hard af4f3a5
cd $PLUG_HOME/vim-fugitive/ && git reset --hard 0374322
cd $PLUG_HOME/vim-gitgutter/ && git reset --hard 1e82019
cd $PLUG_HOME/vim-haml/ && git reset --hard 204e327
cd $PLUG_HOME/vim-jsdoc/ && git reset --hard 56d3c5b
cd $PLUG_HOME/vim-monokai/ && git reset --hard 168adea
cd $PLUG_HOME/vim-multiple-cursors/ && git reset --hard f948606
cd $PLUG_HOME/vim-node/ && git reset --hard 07a5e9f
cd $PLUG_HOME/vim-puppet/ && git reset --hard d881b93
cd $PLUG_HOME/vim-qargs/ && git reset --hard a5fbc37
cd $PLUG_HOME/vim-rails/ && git reset --hard 7ac6b0b
cd $PLUG_HOME/vim-rake/ && git reset --hard 13533d9
cd $PLUG_HOME/vim-rbenv/ && git reset --hard 79a3316
cd $PLUG_HOME/vim-repeat/ && git reset --hard 2a3c5f8
cd $PLUG_HOME/vim-rspec/ && git reset --hard 65735f6
cd $PLUG_HOME/vim-ruby-refactoring/ && git reset --hard 6447a4d
cd $PLUG_HOME/vim-ruby/ && git reset --hard 5bc55be
cd $PLUG_HOME/vim-signature/ && git reset --hard 3bc19dc
cd $PLUG_HOME/vim-sneak/ && git reset --hard 2d9be7b
cd $PLUG_HOME/vim-snippets/ && git reset --hard 0ee4b84
cd $PLUG_HOME/vim-surround/ && git reset --hard fa433e0
cd $PLUG_HOME/vim-tags/ && git reset --hard 2326af6
cd $PLUG_HOME/vim-textobj-comment/ && git reset --hard 58ae457
cd $PLUG_HOME/vim-textobj-entire/ && git reset --hard 41c12e1
cd $PLUG_HOME/vim-textobj-indent/ && git reset --hard deb7686
cd $PLUG_HOME/vim-textobj-line/ && git reset --hard f8ab33c
cd $PLUG_HOME/vim-textobj-rubyblock/ && git reset --hard b5b84e4
cd $PLUG_HOME/vim-textobj-user/ && git reset --hard 5256321
cd $PLUG_HOME/vim-togglelist/ && git reset --hard cafedc4
cd $PLUG_HOME/vim-unimpaired/ && git reset --hard 1bf6f16
cd $PLUG_HOME/vim-unite-history/ && git reset --hard 73c766a
cd $PLUG_HOME/vimfiler.vim/ && git reset --hard 0986007
cd $PLUG_HOME/vimshell.vim/ && git reset --hard 2c319d3
cd $PLUG_HOME/vimux/ && git reset --hard 50254fa

