language: objective-c
notifications:
  email:
    on_success: never
    on_failure: change
script: 'curl -s https://raw.githubusercontent.com/minodisk/js-refactor/develop/spec/ci/build-package.sh | sh'
