language: objective-c

osx_image: beta-xcode6.2

git:
  depth: 10

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a7cbe520877895f3154a
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: true     # default: false
  email:
    on_success: never
    on_failure: change

script: sh build-package.sh

env:
    - APM_TEST_PACKAGES="language-marko language-tss language-html-swig language-svg"

cache:
    - pip
    - directories:
        - node_modules
        - $HOME/.atom

before_install:
  # Update Homebrew
  - brew update
  - brew tap homebrew/dupes
  - brew tap homebrew/versions
  # Ruby language support
  # - gem install ruby-beautify --verbose
  - gem install rubocop
  - gem install htmlbeautifier
  - gem install puppet-lint
  # Python language support
  - brew install python
  - pip install --upgrade autopep8
  # SQL language support
  - pip install --upgrade sqlparse
  # Java, C, C++, C#, Objective-C, D, Pawn, Vala
  - brew install uncrustify
  # PHP
  - brew tap homebrew/homebrew-php
  - brew install php56 || true
  - brew gist-logs php56 || true
  - echo -e "\n[Phar]\nphar.readonly = Off\n" >> /usr/local/etc/php/5.6/php.ini
  - brew install php-cs-fixer || true
  - brew gist-logs php-cs-fixer || true
  # CoffeeScript
  - npm install coffee-formatter
